# Production Docker Compose Configuration
# Usage: docker-compose -f docker-compose.prod.yml up -d

version: '3.8'

services:
  frontend:
    build: 
      context: ./Development/FE
      dockerfile: Dockerfile
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS (if using SSL)
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${API_URL:-http://backend:3001}
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  backend:
    build:
      context: ./Development/BE
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    volumes:
      - backend-data:/app/prisma
      - ./logs:/app/logs
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  backend-data:

