version: '3.8'

services:
  frontend:
    build: 
      context: ./Development/FE
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./Development/BE
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=your-secret-key-change-in-production
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost
    volumes:
      - backend-data:/app/prisma
    restart: unless-stopped

volumes:
  backend-data:

